# File Location from project root:
# gradle.properties

# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft Properties
minecraft_version=26.1
minecraft_version_range=[26.1]

# NeoForge Properties
neo_version=26.1.0.19-beta

# Fabric Properties
# Source: https://fabricmc.net/develop/ -> go to "Latest Versions"
fabric_loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.145.1+26.1

## Mod Properties
mod_id=carve_it_up
mod_name=Carve It Up
mod_license=MMPLv2
mod_version=1.0.0-26.1
mod_group_id=nl.patrick.carve_it_up
