// File Location from project root:
// settings.gradle
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        // Location of the Gradle 'net.fabricmc.fabric-loom' plugin
        maven { url = "https://maven.fabricmc.net/" }
    }
    plugins {
        id 'net.fabricmc.fabric-loom' version "${loom_version}"
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = "carve_it_up"

include("common")
include("neoforge")
include("fabric")