// File Location from project root:
// common/build.gradle
plugins {
    id 'java-library'
    id 'net.neoforged.moddev'
    id 'net.fabricmc.fabric-loom-companion'
}

base {
    archivesName = "${mod_id}-common"
}

neoForge {
    // Look for versions on https://projects.neoforged.net/neoforged/neoform
    // This turns on ModDevGradle's official "Vanilla-Mode" for cross-loader subprojects!
    neoFormVersion = "26.1-1"
//    neoFormVersion = "26.1.0.19-beta"

    // Optional: You can still generate IDE runs for testing plain vanilla right from common
    runs {
        client { client() }
        server { server() }
    }
}

dependencies {
    // This gives access to @Mixin, @Inject, @At, etc.
    compileOnly 'org.spongepowered:mixin:0.8.5'

    // Ensure to also include the primary Minecraft/loader dependencies
}
